const facilities=[
{id:1,type:"hospital",name:"AIIMS Nagpur",area:"MIHAN",address:"Plot No. 2, Sector-20, MIHAN, Nagpur, Maharashtra 441124",phone:"9404044944",lat:21.0860,lng:79.0570,tags:["Government","Multispeciality","Emergency"],source:"AIIMS Nagpur official site",url:"https://aiimsnagpur.edu.in/hospital",details:"AIIMS Nagpur is a tertiary-care institute with public-facing hospital, diagnostic and specialty information.",services:["Emergency & Trauma","Cardiology","Nephrology","Neurosurgery","Radiodiagnosis"],verified:"Public institutional reference"},
{id:2,type:"hospital",name:"Ganga CARE Hospital Limited, Nagpur",area:"Panchsheel Square",address:"3 Farmland, Panchsheel Square, Wardha Road, Nagpur, Maharashtra 440012",phone:"0712-6165656",lat:21.1390,lng:79.0790,tags:["Multispeciality","Critical Care","Emergency"],source:"CARE Hospitals official site",url:"https://www.carehospitals.com/hospital-detail/care-super-specialty-hospital-nagpur",details:"CARE's official Nagpur page lists a multispeciality hospital at Panchsheel Square with critical-care facilities.",services:["Cardiac Sciences","Nephrology","Neurosciences","Oncology","Orthopaedics","Pulmonology","Urology"],verified:"Public institutional reference"},
{id:3,type:"hospital",name:"Max Super Speciality Hospital, Nagpur",area:"Mankapur",address:"232, Mankapur, Koradi Rd, Byramji Town, Nagpur, Maharashtra 440030",phone:"+917127120000",lat:21.1832,lng:79.0610,tags:["Hospital","24×7 listing"],source:"Local business directory",url:"https://www.google.com/maps/search/?api=1&query=Max+Super+Speciality+Hospital+Nagpur",details:"Local directory reference included for the academic prototype.",services:["Hospital services"],verified:"Local listing — verify directly"},
{id:4,type:"hospital",name:"Orange City Hospital & Research Institute",area:"Khamla Road",address:"19, Khamla Road, Veer Sawarkar Square, Nagpur 440015",phone:"",lat:21.1200,lng:79.0800,tags:["Private Hospital","24×7 listing"],source:"Local business directory",url:"https://www.google.com/maps/search/?api=1&query=Orange+City+Hospital+Nagpur",details:"Local directory reference included for the academic prototype.",services:["Hospital services"],verified:"Local listing — verify directly"},
{id:5,type:"hospital",name:"Arihant Multispeciality Hospital",area:"Untkhana",address:"Opp. Capitol Heights, near VR Mall, Baidyanath Square, Untkhana, Nagpur 440026",phone:"+917126656666",lat:21.1290,lng:79.0830,tags:["Multispeciality","24×7 listing"],source:"Local business directory",url:"https://www.google.com/maps/search/?api=1&query=Arihant+Multispeciality+Hospital+Nagpur",details:"Local directory reference included for the academic prototype.",services:["Hospital services"],verified:"Local listing — verify directly"},
{id:6,type:"blood",name:"Jeevan Jyoti Blood Bank",area:"Laxminagar",address:"J-12, besides Dhruv Diagnostics, Laxminagar, Nagpur 440022",phone:"+917122230876",lat:21.1300,lng:79.0620,tags:["Blood Bank"],source:"Local business directory",url:"https://www.google.com/maps/search/?api=1&query=Jeevan+Jyoti+Blood+Bank+Nagpur",details:"Local directory reference for the Blood Connect module.",services:["Blood bank"],verified:"Local listing — verify directly"},
{id:7,type:"blood",name:"Dr Hedgewar Blood Bank",area:"Dharampeth Extension",address:"184/2, Baji Prabhu Deshpande Chowk, Dharampeth Extension, Nagpur 440010",phone:"+919922407171",lat:21.1450,lng:79.0520,tags:["Blood Bank"],source:"Local business directory",url:"https://www.google.com/maps/search/?api=1&query=Dr+Hedgewar+Blood+Bank+Nagpur",details:"Local directory reference for the Blood Connect module.",services:["Blood bank"],verified:"Local listing — verify directly"},
{id:8,type:"diagnostic",name:"Dhande Diagnostic Centre",area:"Ramdaspeth",address:"Ramdaspeth, Nagpur, Maharashtra 440010",phone:"",lat:21.1370,lng:79.0730,tags:["Diagnostic"],source:"Local business directory",url:"https://www.google.com/maps/search/?api=1&query=Dhande+Diagnostic+Centre+Nagpur",details:"Local diagnostic-centre reference for the academic prototype.",services:["Diagnostics"],verified:"Local listing — verify directly"},
{id:9,type:"diagnostic",name:"STAR Imaging & Diagnostics",area:"Ramdaspeth",address:"Midas Heights, Central Bazar Road, Ramdaspeth, Nagpur 440010",phone:"+918600010686",lat:21.1378,lng:79.0715,tags:["Imaging","3T MRI"],source:"Local business directory",url:"https://www.google.com/maps/search/?api=1&query=STAR+Imaging+Diagnostics+Nagpur",details:"Local imaging-centre reference for the academic prototype.",services:["MRI","Diagnostics"],verified:"Local listing — verify directly"}
];
const doctors=[
{name:"Dr. Siddharth Dubhashi",spec:"General Surgery",hospital:"AIIMS Nagpur",qual:"Professor & Head",source:"AIIMS Nagpur official directory",url:"https://aiimsnagpur.edu.in/directory"},
{name:"Dr. Arijit Kumar Ghosh",spec:"Cardiology",hospital:"AIIMS Nagpur",qual:"Professor & Head",source:"AIIMS Nagpur official directory",url:"https://aiimsnagpur.edu.in/directory"},
{name:"Dr. Anand Chellappan",spec:"Nephrology",hospital:"AIIMS Nagpur",qual:"Assistant Professor and In-charge",source:"AIIMS Nagpur official directory",url:"https://aiimsnagpur.edu.in/directory"},
{name:"Dr. Alok Umredkar",spec:"Neurosurgery",hospital:"AIIMS Nagpur",qual:"Associate Professor",source:"AIIMS Nagpur official directory",url:"https://aiimsnagpur.edu.in/directory"},
{name:"Dr. Mahendra Chauhan",spec:"Emergency and Trauma",hospital:"AIIMS Nagpur",qual:"Professor & Head",source:"AIIMS Nagpur official directory",url:"https://aiimsnagpur.edu.in/directory"},
{name:"Dr. Akash Mahalle",spec:"Radiology",hospital:"Ganga CARE Hospital Limited, Nagpur",qual:"Consultant — MBBS, MD (Radiology)",source:"CARE Hospitals official doctor directory",url:"https://www.carehospitals.com/doctor-list/nagpur"},
{name:"Dr. Ankur Sanghvi",spec:"Neurosurgery",hospital:"Ganga CARE Hospital Limited, Nagpur",qual:"Consultant — MBBS, MS, MCh (Neuro)",source:"CARE Hospitals official doctor directory",url:"https://www.carehospitals.com/doctor-list/nagpur"},
{name:"Dr. Priyesh Dhoke",spec:"Orthopaedics, Spine Surgery",hospital:"Ganga CARE Hospital Limited, Nagpur",qual:"Sr. Consultant",source:"CARE Hospitals official doctor directory",url:"https://www.carehospitals.com/doctor-list/nagpur"},
{name:"Dr. Utkarsh Deshmukh",spec:"Nephrology",hospital:"Ganga CARE Hospital Limited, Nagpur",qual:"Consultant Nephrologist and Transplant Physician",source:"CARE Hospitals official doctor directory",url:"https://www.carehospitals.com/doctor-list/nagpur"}
];

function esc(s){return String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]))}
function go(h){location.hash=h.replace(/^#/,"#")}
function notice(msg){const t=document.getElementById("toast");t.textContent=msg;t.classList.add("show");setTimeout(()=>t.classList.remove("show"),3000)}
function card(f){return `<article class="card"><div class="card-top"><div><small>${esc(f.area)}</small><h3>${esc(f.name)}</h3></div><span class="badge">${esc(f.type)}</span></div><p>${esc(f.address)}</p><div class="tags">${f.tags.map(x=>`<span class="tag">${esc(x)}</span>`).join("")}</div><small>${esc(f.verified)}</small><div class="actions"><a href="#hospital-detail/${f.id}">View details</a>${f.phone?`<a href="tel:${esc(f.phone)}">☎ Call</a>`:""}<a target="_blank" rel="noopener" href="https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(f.address)}">📍 Directions</a></div></article>`}
function renderFeatured(){document.getElementById("featuredHospitals").innerHTML=facilities.filter(x=>x.type==="hospital").slice(0,3).map(card).join("")}
function renderHospitals(){const q=(document.getElementById("hospitalSearch")?.value||"").toLowerCase();const type=document.getElementById("facilityFilter")?.value||"all";const list=facilities.filter(f=>(type==="all"||f.type===type)&&`${f.name} ${f.area} ${f.tags.join(" ")}`.toLowerCase().includes(q));document.getElementById("hospitalList").innerHTML=list.map(card).join("")||"<div class='about-card'><h3>No results</h3><p>Try another search.</p></div>"}
function doctorCard(d){return `<article class="card"><div class="doctor-avatar">👨‍⚕️</div><small>${esc(d.spec)}</small><h3>${esc(d.name)}</h3><p>${esc(d.hospital)}</p><div class="tags"><span class="tag">${esc(d.qual)}</span></div><small>${esc(d.source)}</small><div class="actions"><a href="#doctor-detail/${doctors.indexOf(d)}">View profile</a><a target="_blank" rel="noopener" href="${d.url}">↗ Verify source</a><a href="#appointments" onclick="prefillDoctor('${esc(d.name)}')">📅 Demo booking</a></div></article>`}
function renderDoctors(){const q=(document.getElementById("doctorSearch")?.value||"").toLowerCase();document.getElementById("doctorList").innerHTML=doctors.filter(d=>`${d.name} ${d.spec} ${d.hospital}`.toLowerCase().includes(q)).map(doctorCard).join("")}
function renderHospitalDetail(id){const f=facilities.find(x=>x.id===Number(id));if(!f)return;document.getElementById("hospitalDetail").innerHTML=`<div class="detail-hero"><article class="detail-main"><span class="eyebrow">${esc(f.type)} • ${esc(f.area)}</span><h1>${esc(f.name)}</h1><p>${esc(f.details)}</p><div class="detail-actions"><a class="primary" href="https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(f.address)}" target="_blank">📍 Get directions</a>${f.phone?`<a class="outline" href="tel:${esc(f.phone)}">☎ Call</a>`:""}<a class="outline" href="${f.url}" target="_blank">↗ Source</a></div><div class="detail-grid">${f.services.map(s=>`<div class="info-box"><b>${esc(s)}</b><span>Listed service / reference</span></div>`).join("")}</div><p class="source-note">Source: ${esc(f.source)} • Status: ${esc(f.verified)}. This page does not represent live availability.</p></article><aside class="detail-side"><h3>Location</h3><p>📍 ${esc(f.address)}</p><div id="detailMap" style="height:330px;border-radius:15px;overflow:hidden"></div></aside></div>`;setTimeout(()=>{const m=L.map("detailMap").setView([f.lat,f.lng],14);L.tileLayer("https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png",{attribution:"© OpenStreetMap contributors"}).addTo(m);L.marker([f.lat,f.lng]).addTo(m).bindPopup(esc(f.name)).openPopup()},50)}
function renderDoctorDetail(i){const d=doctors[Number(i)];if(!d)return;document.getElementById("doctorDetail").innerHTML=`<div class="doctor-detail"><article class="detail-main"><div class="doctor-avatar">👨‍⚕️</div><span class="eyebrow">${esc(d.spec)}</span><h1>${esc(d.name)}</h1><h3>${esc(d.hospital)}</h3><p>${esc(d.qual)}</p><div class="detail-grid"><div class="info-box"><b>Specialty</b><span>${esc(d.spec)}</span></div><div class="info-box"><b>Institution</b><span>${esc(d.hospital)}</span></div></div><div class="detail-actions"><a class="primary" href="#appointments" onclick="prefillDoctor('${esc(d.name)}')">📅 Demo appointment</a><a class="outline" href="${d.url}" target="_blank">↗ Verify official profile</a></div><p class="source-note">Reference: ${esc(d.source)}. Current schedule/availability is not implied.</p></article><aside class="detail-side"><h3>About this profile</h3><p>MEDORA displays publicly listed professional information for academic demonstration. Users should verify current details directly with the institution.</p></aside></div>`}
let map,markers=[];
function initMap(){if(!window.L)return;if(map){map.invalidateSize();return}map=L.map("leafletMap").setView([21.1458,79.0882],12);L.tileLayer("https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png",{maxZoom:19,attribution:"© OpenStreetMap contributors"}).addTo(map);document.querySelectorAll(".legend input").forEach(x=>x.addEventListener("change",renderMap));renderMap()}
function renderMap(){if(!map)return;markers.forEach(m=>map.removeLayer(m));markers=[];const enabled=[...document.querySelectorAll(".legend input:checked")].map(x=>x.dataset.type);facilities.filter(f=>enabled.includes(f.type)).forEach(f=>{const m=L.marker([f.lat,f.lng]).addTo(map).bindPopup(`<b>${esc(f.name)}</b><br>${esc(f.area)}<br><a href="#hospital-detail/${f.id}">View details</a>`);markers.push(m)});document.getElementById("mapList").innerHTML=facilities.filter(f=>enabled.includes(f.type)).map(f=>`<div class="map-mini" onclick="map.setView([${f.lat},${f.lng}],15)"><b>${esc(f.name)}</b><small>${esc(f.area)}</small></div>`).join("")}
function showService(type){document.getElementById("serviceResults").innerHTML=facilities.filter(x=>x.type===type).map(card).join("");go("#services")}
function locateUser(){if(!navigator.geolocation){notice("Geolocation is not supported.");return}navigator.geolocation.getCurrentPosition(p=>{notice("Location permission received.");if(map){map.setView([p.coords.latitude,p.coords.longitude],14);L.marker([p.coords.latitude,p.coords.longitude]).addTo(map).bindPopup("You are here").openPopup()}},()=>notice("Location permission was not granted."))}
function globalSearch(){const q=document.getElementById("globalSearch").value.trim();document.getElementById("hospitalSearch").value=q;document.getElementById("doctorSearch").value=q;go("#hospitals");renderHospitals()}
function prefillDoctor(name){setTimeout(()=>{const el=document.getElementById("bookingDoctor");if(el)el.value=name},80)}
function setupBooking(){document.getElementById("bookingHospital").innerHTML=facilities.filter(f=>f.type==="hospital").map(f=>`<option>${esc(f.name)}</option>`).join("");document.getElementById("bookingDoctor").innerHTML=doctors.map(d=>`<option>${esc(d.name)}</option>`).join("")}
document.getElementById("bookingForm").addEventListener("submit",e=>{e.preventDefault();const id="WC-DEMO-"+Math.floor(10000+Math.random()*90000);const data={id,name:document.getElementById("patientName").value,email:localStorage.getItem("wc_email")||"",hospital:document.getElementById("bookingHospital").value,doctor:document.getElementById("bookingDoctor").value};localStorage.setItem("wc_booking",JSON.stringify(data));document.getElementById("bookingResult").innerHTML=`<div class="about-card"><h2>✓ Demo booking created</h2><p>Booking ID: <b>${id}</b></p><p>${esc(data.name)} • ${esc(data.hospital)} • ${esc(data.doctor)}</p><p><b>Demo only:</b> No hospital was contacted.</p></div>`;notice("Demo appointment created.")});
function login(email,name,role){localStorage.setItem("wc_email",email);localStorage.setItem("wc_name",name);localStorage.setItem("wc_role",role);notice("Logged in as "+role);go(role==="admin"?"#admin":"#profile");updateProfile()}
function updateProfile(){const n=localStorage.getItem("wc_name");const e=localStorage.getItem("wc_email");document.getElementById("profileName").textContent=n||"Guest";document.getElementById("profileEmail").textContent=e||"Not logged in";const b=JSON.parse(localStorage.getItem("wc_booking")||"null");document.getElementById("profileBooking").textContent=b?`${b.id} • ${b.doctor}`:"No demo booking yet.";document.getElementById("adminBookings").textContent=b?"01":"00"}
document.getElementById("loginForm").addEventListener("submit",e=>{e.preventDefault();login(document.getElementById("loginEmail").value,"Demo User","user")});
document.getElementById("registerForm").addEventListener("submit",e=>{e.preventDefault();login(document.getElementById("regEmail").value,document.getElementById("regName").value,"user")});
function demoAdmin(){login("admin@medora.local","MEDORA Admin","admin")}
function logout(){localStorage.removeItem("wc_email");localStorage.removeItem("wc_name");localStorage.removeItem("wc_role");notice("Logged out.");go("#home")}
document.getElementById("loginBtn").onclick=()=>go("#login");document.getElementById("menuBtn").onclick=()=>{const n=document.getElementById("nav");n.style.display=n.style.display==="flex"?"none":"flex"};
function route(){let raw=location.hash.replace("#","")||"home";const parts=raw.split("/");let id=parts[0];document.querySelectorAll(".page").forEach(p=>p.classList.toggle("active",p.id===id));if(id==="hospital-detail")renderHospitalDetail(parts[1]);if(id==="doctor-detail")renderDoctorDetail(parts[1]);if(id==="map")setTimeout(initMap,80);if(id==="profile")updateProfile();if(id==="admin"&&localStorage.getItem("wc_role")!=="admin"){notice("Use Admin Demo login first.");go("#login");return}window.scrollTo({top:0,behavior:"smooth"})}
window.addEventListener("hashchange",route);setupBooking();renderFeatured();renderHospitals();renderDoctors();updateProfile();route();
